---
http_interactions:
- request:
    method: post
    uri: http://127.0.0.1:8001/api/v1/namespaces/workflows/pods/mistral:8989/proxy/v2/environments
    body:
      encoding: UTF-8
      string: '{"name":"test","variables":"{\"foo\":\"bar\"}"}'
    headers:
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: Created
    headers:
      Content-Length:
      - '154'
      Content-Type:
      - application/json
      Date:
      - Mon, 11 Sep 2017 18:16:10 GMT
    body:
      encoding: UTF-8
      string: '{"created_at": "2017-09-11 18:16:10", "scope": "private", "variables":
        "{\"foo\": \"bar\"}", "id": "139367e1-d03f-4abd-9273-bced4f9f9f36", "name":
        "test"}'
    http_version: 
  recorded_at: Mon, 11 Sep 2017 18:17:37 GMT
- request:
    method: post
    uri: http://127.0.0.1:8001/api/v1/namespaces/workflows/pods/mistral:8989/proxy/v2/workflows
    body:
      encoding: UTF-8
      string: "---\n      version: \"2.0\"\n      echo_test:\n        type: reverse\n
        \       tasks:\n          echo:\n            action: std.echo output=\"ok\"\n
        \   "
    headers:
      Content-Type:
      - text/plain
  response:
    status:
      code: 201
      message: Created
    headers:
      Content-Length:
      - '370'
      Content-Type:
      - application/json
      Date:
      - Mon, 11 Sep 2017 18:16:10 GMT
    body:
      encoding: UTF-8
      string: '{"workflows": [{"definition": "---\n      version: \"2.0\"\n      echo_test:\n        type:
        reverse\n        tasks:\n          echo:\n            action: std.echo output=\"ok\"\n    ",
        "name": "echo_test", "tags": [], "created_at": "2017-09-11 18:16:10", "scope":
        "private", "input": "", "project_id": "<default-project>", "id": "b3d79c8d-7916-4c87-99bf-9f596ccda4de"}]}'
    http_version: 
  recorded_at: Mon, 11 Sep 2017 18:17:37 GMT
- request:
    method: post
    uri: http://127.0.0.1:8001/api/v1/namespaces/workflows/pods/mistral:8989/proxy/v2/executions
    body:
      encoding: UTF-8
      string: '{"workflow_id":"b3d79c8d-7916-4c87-99bf-9f596ccda4de","params":{"env":"test","task_name":"echo"}}'
    headers:
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: Created
    headers:
      Content-Length:
      - '390'
      Content-Type:
      - application/json
      Date:
      - Mon, 11 Sep 2017 18:16:10 GMT
    body:
      encoding: UTF-8
      string: '{"state_info": null, "created_at": "2017-09-11 18:16:10", "description":
        "", "state": "RUNNING", "workflow_name": "echo_test", "task_execution_id":
        null, "updated_at": "2017-09-11 18:16:10", "workflow_id": "b3d79c8d-7916-4c87-99bf-9f596ccda4de",
        "params": "{\"task_name\": \"echo\", \"env\": {\"foo\": \"bar\"}}", "output":
        "{}", "input": "{}", "id": "5348ae6c-aab7-4db2-b3f6-c09c9e92f004"}'
    http_version: 
  recorded_at: Mon, 11 Sep 2017 18:17:37 GMT
- request:
    method: delete
    uri: http://127.0.0.1:8001/api/v1/namespaces/workflows/pods/mistral:8989/proxy/v2/environments/test
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 204
      message: No Content
    headers:
      Date:
      - Mon, 11 Sep 2017 18:16:10 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Mon, 11 Sep 2017 18:17:37 GMT
- request:
    method: delete
    uri: http://127.0.0.1:8001/api/v1/namespaces/workflows/pods/mistral:8989/proxy/v2/workflows/b3d79c8d-7916-4c87-99bf-9f596ccda4de
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 204
      message: No Content
    headers:
      Date:
      - Mon, 11 Sep 2017 18:16:11 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Mon, 11 Sep 2017 18:17:38 GMT
recorded_with: VCR 3.0.3
