---
http_interactions:
- request:
    method: post
    uri: http://localhost:8989/v2/environments
    body:
      encoding: UTF-8
      string: '{"name":"test","variables":"{\"foo\":\"bar\"}"}'
    headers:
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Content-Length:
      - '154'
      Content-Type:
      - application/json
      Date:
      - Sat, 06 Feb 2021 21:59:34 GMT
    body:
      encoding: UTF-8
      string: '{"created_at": "2021-02-06 21:59:34", "scope": "private", "variables":
        "{\"foo\": \"bar\"}", "id": "2e76cea3-5686-46de-b39d-3d50619cdccd", "name":
        "test"}'
    http_version:
  recorded_at: Sat, 06 Feb 2021 21:59:34 GMT
- request:
    method: post
    uri: http://localhost:8989/v2/workflows
    body:
      encoding: UTF-8
      string: "---\n      version: \"2.0\"\n      echo_test:\n        type: reverse\n
        \       tasks:\n          echo:\n            action: std.echo output=\"ok\"\n
        \   "
    headers:
      Content-Type:
      - text/plain
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Content-Length:
      - '370'
      Content-Type:
      - application/json
      Date:
      - Sat, 06 Feb 2021 21:59:34 GMT
    body:
      encoding: UTF-8
      string: '{"workflows": [{"definition": "---\n      version: \"2.0\"\n      echo_test:\n        type:
        reverse\n        tasks:\n          echo:\n            action: std.echo output=\"ok\"\n    ",
        "name": "echo_test", "tags": [], "created_at": "2021-02-06 21:59:34", "scope":
        "private", "input": "", "project_id": "<default-project>", "id": "167178aa-0746-4979-843f-d824d3db77c0"}]}'
    http_version:
  recorded_at: Sat, 06 Feb 2021 21:59:34 GMT
- request:
    method: post
    uri: http://localhost:8989/v2/executions
    body:
      encoding: UTF-8
      string: '{"workflow_id":"167178aa-0746-4979-843f-d824d3db77c0","params":{"env":"test","task_name":"echo"}}'
    headers:
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Content-Length:
      - '390'
      Content-Type:
      - application/json
      Date:
      - Sat, 06 Feb 2021 21:59:34 GMT
    body:
      encoding: UTF-8
      string: '{"state_info": null, "created_at": "2021-02-06 21:59:34", "description":
        "", "state": "RUNNING", "workflow_name": "echo_test", "task_execution_id":
        null, "updated_at": "2021-02-06 21:59:34", "workflow_id": "167178aa-0746-4979-843f-d824d3db77c0",
        "params": "{\"task_name\": \"echo\", \"env\": {\"foo\": \"bar\"}}", "output":
        "{}", "input": "{}", "id": "862c9a27-2e97-4575-9161-7ce3d2785f88"}'
    http_version:
  recorded_at: Sat, 06 Feb 2021 21:59:34 GMT
- request:
    method: delete
    uri: http://localhost:8989/v2/environments/test
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 204
      message: No Content
    headers:
      Content-Length:
      - '0'
      Date:
      - Sat, 06 Feb 2021 21:59:34 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version:
  recorded_at: Sat, 06 Feb 2021 21:59:34 GMT
- request:
    method: delete
    uri: http://localhost:8989/v2/workflows/167178aa-0746-4979-843f-d824d3db77c0
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 204
      message: No Content
    headers:
      Content-Length:
      - '0'
      Date:
      - Sat, 06 Feb 2021 21:59:35 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version:
  recorded_at: Sat, 06 Feb 2021 21:59:35 GMT
recorded_with: VCR 5.1.0
