---
http_interactions:
- request:
    method: post
    uri: http://localhost:8989/v2/environments
    body:
      encoding: UTF-8
      string: '{"name":"test","variables":"{\"foo\":\"bar\"}"}'
    headers:
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Content-Length:
      - '154'
      Content-Type:
      - application/json
      Date:
      - Sat, 06 Feb 2021 21:59:29 GMT
    body:
      encoding: UTF-8
      string: '{"created_at": "2021-02-06 21:59:29", "scope": "private", "variables":
        "{\"foo\": \"bar\"}", "id": "f6c30f9e-3070-467d-b4ae-b1a049e9819c", "name":
        "test"}'
    http_version:
  recorded_at: Sat, 06 Feb 2021 21:59:29 GMT
- request:
    method: post
    uri: http://localhost:8989/v2/workflows
    body:
      encoding: UTF-8
      string: |
        ---
          version: "2.0"
          echo_test:
            type: direct
            tasks:
              echo:
                action: std.echo output="ok"
    headers:
      Content-Type:
      - text/plain
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Content-Length:
      - '341'
      Content-Type:
      - application/json
      Date:
      - Sat, 06 Feb 2021 21:59:29 GMT
    body:
      encoding: UTF-8
      string: '{"workflows": [{"definition": "---\n  version: \"2.0\"\n  echo_test:\n    type:
        direct\n    tasks:\n      echo:\n        action: std.echo output=\"ok\"\n",
        "name": "echo_test", "tags": [], "created_at": "2021-02-06 21:59:29", "scope":
        "private", "input": "", "project_id": "<default-project>", "id": "6f95c342-bfcd-405d-8430-1505bf0cf583"}]}'
    http_version:
  recorded_at: Sat, 06 Feb 2021 21:59:29 GMT
- request:
    method: post
    uri: http://localhost:8989/v2/executions
    body:
      encoding: UTF-8
      string: '{"workflow_id":"6f95c342-bfcd-405d-8430-1505bf0cf583","params":{"env":"test"}}'
    headers:
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Content-Length:
      - '365'
      Content-Type:
      - application/json
      Date:
      - Sat, 06 Feb 2021 21:59:29 GMT
    body:
      encoding: UTF-8
      string: '{"state_info": null, "created_at": "2021-02-06 21:59:29", "description":
        "", "state": "RUNNING", "workflow_name": "echo_test", "task_execution_id":
        null, "updated_at": "2021-02-06 21:59:29", "workflow_id": "6f95c342-bfcd-405d-8430-1505bf0cf583",
        "params": "{\"env\": {\"foo\": \"bar\"}}", "output": "{}", "input": "{}",
        "id": "6bd0186f-e78b-4ad3-92df-dadd2667e945"}'
    http_version:
  recorded_at: Sat, 06 Feb 2021 21:59:29 GMT
- request:
    method: delete
    uri: http://localhost:8989/v2/environments/test
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 204
      message: No Content
    headers:
      Content-Length:
      - '0'
      Date:
      - Sat, 06 Feb 2021 21:59:29 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version:
  recorded_at: Sat, 06 Feb 2021 21:59:29 GMT
- request:
    method: delete
    uri: http://localhost:8989/v2/workflows/6f95c342-bfcd-405d-8430-1505bf0cf583
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 204
      message: No Content
    headers:
      Content-Length:
      - '0'
      Date:
      - Sat, 06 Feb 2021 21:59:30 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version:
  recorded_at: Sat, 06 Feb 2021 21:59:30 GMT
recorded_with: VCR 5.1.0
