---
http_interactions:
- request:
    method: get
    uri: http://localhost:8989/v2/
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Length:
      - '35'
      Content-Type:
      - application/json
      Date:
      - Sat, 06 Feb 2021 21:59:43 GMT
    body:
      encoding: UTF-8
      string: '{"uri": "http://localhost:8989/v2"}'
    http_version:
  recorded_at: Sat, 06 Feb 2021 21:59:43 GMT
recorded_with: VCR 5.1.0
