---
http_interactions:
- request:
    method: post
    uri: http://127.0.0.1:8001/api/v1/namespaces/workflows/pods/mistral:8989/proxy/v2/environments
    body:
      encoding: UTF-8
      string: '{"name":"test","variables":"{\"output\":\"environment_test\"}"}'
    headers:
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: Created
    headers:
      Content-Length:
      - '170'
      Content-Type:
      - application/json
      Date:
      - Thu, 13 Jul 2017 17:18:43 GMT
    body:
      encoding: UTF-8
      string: '{"created_at": "2017-07-13 17:18:43", "scope": "private", "variables":
        "{\"output\": \"environment_test\"}", "id": "e2399c11-a148-4274-9fc3-e351112e1834",
        "name": "test"}'
    http_version: 
  recorded_at: Thu, 13 Jul 2017 17:19:23 GMT
- request:
    method: delete
    uri: http://127.0.0.1:8001/api/v1/namespaces/workflows/pods/mistral:8989/proxy/v2/environments/test
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 204
      message: No Content
    headers:
      Date:
      - Thu, 13 Jul 2017 17:18:44 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Thu, 13 Jul 2017 17:19:24 GMT
recorded_with: VCR 3.0.3
