---
http_interactions:
- request:
    method: post
    uri: http://localhost:8989/v2/environments
    body:
      encoding: UTF-8
      string: '{"name":"test","variables":"{\"output\":\"environment_test\"}"}'
    headers:
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Content-Length:
      - '170'
      Content-Type:
      - application/json
      Date:
      - Sat, 06 Feb 2021 21:59:22 GMT
    body:
      encoding: UTF-8
      string: '{"created_at": "2021-02-06 21:59:22", "scope": "private", "variables":
        "{\"output\": \"environment_test\"}", "id": "d7fe63ec-5513-41c0-b1c0-7eb0af6f907b",
        "name": "test"}'
    http_version:
  recorded_at: Sat, 06 Feb 2021 21:59:22 GMT
- request:
    method: get
    uri: http://localhost:8989/v2/environments/test
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Length:
      - '211'
      Content-Type:
      - application/json
      Date:
      - Sat, 06 Feb 2021 21:59:22 GMT
    body:
      encoding: UTF-8
      string: '{"description": null, "created_at": "2021-02-06 21:59:22", "updated_at":
        null, "id": "d7fe63ec-5513-41c0-b1c0-7eb0af6f907b", "scope": "private", "variables":
        "{\"output\": \"environment_test\"}", "name": "test"}'
    http_version:
  recorded_at: Sat, 06 Feb 2021 21:59:22 GMT
- request:
    method: delete
    uri: http://localhost:8989/v2/environments/test
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 204
      message: No Content
    headers:
      Content-Length:
      - '0'
      Date:
      - Sat, 06 Feb 2021 21:59:23 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version:
  recorded_at: Sat, 06 Feb 2021 21:59:23 GMT
recorded_with: VCR 5.1.0
