---
http_interactions:
- request:
    method: post
    uri: http://127.0.0.1:8001/api/v1/namespaces/workflows/pods/mistral:8989/proxy/v2/environments
    body:
      encoding: UTF-8
      string: '{"name":"test_with_input","variables":"{\"foo\":\"bar\"}"}'
    headers:
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: Created
    headers:
      Content-Length:
      - '165'
      Content-Type:
      - application/json
      Date:
      - Thu, 14 Dec 2017 19:55:04 GMT
    body:
      encoding: UTF-8
      string: '{"created_at": "2017-12-14 19:55:04", "scope": "private", "variables":
        "{\"foo\": \"bar\"}", "id": "965a0e9f-59a6-4fb0-823d-614d954b2eef", "name":
        "test_with_input"}'
    http_version: 
  recorded_at: Thu, 14 Dec 2017 19:55:04 GMT
- request:
    method: post
    uri: http://127.0.0.1:8001/api/v1/namespaces/workflows/pods/mistral:8989/proxy/v2/workflows
    body:
      encoding: UTF-8
      string: "---\n  version: \"2.0\"\n  echo_test_with_input:\n    type: direct\n
        \   input:\n      - key\n    tasks:\n      echo:\n        action: std.echo
        output=\"ok\"\n    "
    headers:
      Content-Type:
      - text/plain
  response:
    status:
      code: 201
      message: Created
    headers:
      Content-Length:
      - '395'
      Content-Type:
      - application/json
      Date:
      - Thu, 14 Dec 2017 19:55:04 GMT
    body:
      encoding: UTF-8
      string: '{"workflows": [{"definition": "---\n  version: \"2.0\"\n  echo_test_with_input:\n    type:
        direct\n    input:\n      - key\n    tasks:\n      echo:\n        action:
        std.echo output=\"ok\"\n    ", "name": "echo_test_with_input", "tags": [],
        "created_at": "2017-12-14 19:55:04", "scope": "private", "input": "key", "project_id":
        "<default-project>", "id": "08386ae2-4eb1-4e55-871a-2c3e802dd8ee"}]}'
    http_version: 
  recorded_at: Thu, 14 Dec 2017 19:55:04 GMT
- request:
    method: post
    uri: http://127.0.0.1:8001/api/v1/namespaces/workflows/pods/mistral:8989/proxy/v2/executions
    body:
      encoding: UTF-8
      string: '{"workflow_id":"08386ae2-4eb1-4e55-871a-2c3e802dd8ee","params":{"env":"test_with_input"},"input":{"key":"value"}}'
    headers:
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: Created
    headers:
      Content-Length:
      - '394'
      Content-Type:
      - application/json
      Date:
      - Thu, 14 Dec 2017 19:55:04 GMT
    body:
      encoding: UTF-8
      string: '{"state_info": null, "created_at": "2017-12-14 19:55:04", "description":
        "", "state": "RUNNING", "workflow_name": "echo_test_with_input", "task_execution_id":
        null, "updated_at": "2017-12-14 19:55:04", "workflow_id": "08386ae2-4eb1-4e55-871a-2c3e802dd8ee",
        "params": "{\"env\": {\"foo\": \"bar\"}}", "output": "{}", "input": "{\"key\":
        \"value\"}", "id": "691ffcfe-ee00-4d28-bbc3-835171ee69b1"}'
    http_version: 
  recorded_at: Thu, 14 Dec 2017 19:55:04 GMT
- request:
    method: delete
    uri: http://127.0.0.1:8001/api/v1/namespaces/workflows/pods/mistral:8989/proxy/v2/environments/test_with_input
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 204
      message: No Content
    headers:
      Date:
      - Thu, 14 Dec 2017 19:55:04 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Thu, 14 Dec 2017 19:55:04 GMT
- request:
    method: delete
    uri: http://127.0.0.1:8001/api/v1/namespaces/workflows/pods/mistral:8989/proxy/v2/workflows/08386ae2-4eb1-4e55-871a-2c3e802dd8ee
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 204
      message: No Content
    headers:
      Date:
      - Thu, 14 Dec 2017 19:55:05 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Thu, 14 Dec 2017 19:55:05 GMT
recorded_with: VCR 3.0.3
