---
http_interactions:
- request:
    method: post
    uri: http://localhost:8989/v2/environments
    body:
      encoding: UTF-8
      string: '{"name":"test_with_input","variables":"{\"foo\":\"bar\"}"}'
    headers:
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Content-Length:
      - '165'
      Content-Type:
      - application/json
      Date:
      - Sat, 06 Feb 2021 21:59:30 GMT
    body:
      encoding: UTF-8
      string: '{"created_at": "2021-02-06 21:59:30", "scope": "private", "variables":
        "{\"foo\": \"bar\"}", "id": "0628a49a-a08c-4289-8e6a-baba3f50593e", "name":
        "test_with_input"}'
    http_version:
  recorded_at: Sat, 06 Feb 2021 21:59:30 GMT
- request:
    method: post
    uri: http://localhost:8989/v2/workflows
    body:
      encoding: UTF-8
      string: "---\n  version: \"2.0\"\n  echo_test_with_input:\n    type: direct\n
        \   input:\n      - key\n    tasks:\n      echo:\n        action: std.echo
        output=\"ok\"\n    "
    headers:
      Content-Type:
      - text/plain
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Content-Length:
      - '395'
      Content-Type:
      - application/json
      Date:
      - Sat, 06 Feb 2021 21:59:30 GMT
    body:
      encoding: UTF-8
      string: '{"workflows": [{"definition": "---\n  version: \"2.0\"\n  echo_test_with_input:\n    type:
        direct\n    input:\n      - key\n    tasks:\n      echo:\n        action:
        std.echo output=\"ok\"\n    ", "name": "echo_test_with_input", "tags": [],
        "created_at": "2021-02-06 21:59:30", "scope": "private", "input": "key", "project_id":
        "<default-project>", "id": "6c37907f-9d28-4aef-b959-3e4a88b10565"}]}'
    http_version:
  recorded_at: Sat, 06 Feb 2021 21:59:30 GMT
- request:
    method: post
    uri: http://localhost:8989/v2/executions
    body:
      encoding: UTF-8
      string: '{"workflow_id":"6c37907f-9d28-4aef-b959-3e4a88b10565","params":{"env":"test_with_input"},"input":{"key":"value"}}'
    headers:
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Content-Length:
      - '394'
      Content-Type:
      - application/json
      Date:
      - Sat, 06 Feb 2021 21:59:30 GMT
    body:
      encoding: UTF-8
      string: '{"state_info": null, "created_at": "2021-02-06 21:59:30", "description":
        "", "state": "RUNNING", "workflow_name": "echo_test_with_input", "task_execution_id":
        null, "updated_at": "2021-02-06 21:59:30", "workflow_id": "6c37907f-9d28-4aef-b959-3e4a88b10565",
        "params": "{\"env\": {\"foo\": \"bar\"}}", "output": "{}", "input": "{\"key\":
        \"value\"}", "id": "e9193049-7972-478a-a97f-526de760a61e"}'
    http_version:
  recorded_at: Sat, 06 Feb 2021 21:59:30 GMT
- request:
    method: delete
    uri: http://localhost:8989/v2/environments/test_with_input
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 204
      message: No Content
    headers:
      Content-Length:
      - '0'
      Date:
      - Sat, 06 Feb 2021 21:59:30 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version:
  recorded_at: Sat, 06 Feb 2021 21:59:30 GMT
- request:
    method: delete
    uri: http://localhost:8989/v2/workflows/6c37907f-9d28-4aef-b959-3e4a88b10565
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 204
      message: No Content
    headers:
      Content-Length:
      - '0'
      Date:
      - Sat, 06 Feb 2021 21:59:31 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version:
  recorded_at: Sat, 06 Feb 2021 21:59:31 GMT
recorded_with: VCR 5.1.0
