---
http_interactions:
- request:
    method: post
    uri: http://127.0.0.1:8001/api/v1/namespaces/workflows/pods/mistral:8989/proxy/v2/environments
    body:
      encoding: UTF-8
      string: '{"name":"test","variables":"{\"output\":\"environment_test\"}"}'
    headers:
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: Created
    headers:
      Content-Length:
      - '170'
      Content-Type:
      - application/json
      Date:
      - Wed, 13 Dec 2017 21:13:27 GMT
    body:
      encoding: UTF-8
      string: '{"created_at": "2017-12-13 21:13:27", "scope": "private", "variables":
        "{\"output\": \"environment_test\"}", "id": "4174e9ff-09ad-4226-bbb7-8a03da819638",
        "name": "test"}'
    http_version: 
  recorded_at: Wed, 13 Dec 2017 21:13:27 GMT
- request:
    method: get
    uri: http://127.0.0.1:8001/api/v1/namespaces/workflows/pods/mistral:8989/proxy/v2/environments
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Length:
      - '231'
      Content-Type:
      - application/json
      Date:
      - Wed, 13 Dec 2017 21:13:27 GMT
    body:
      encoding: UTF-8
      string: '{"environments": [{"description": null, "created_at": "2017-12-13 21:13:27",
        "updated_at": null, "id": "4174e9ff-09ad-4226-bbb7-8a03da819638", "scope":
        "private", "variables": "{\"output\": \"environment_test\"}", "name": "test"}]}'
    http_version: 
  recorded_at: Wed, 13 Dec 2017 21:13:27 GMT
- request:
    method: delete
    uri: http://127.0.0.1:8001/api/v1/namespaces/workflows/pods/mistral:8989/proxy/v2/environments/test
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 204
      message: No Content
    headers:
      Date:
      - Wed, 13 Dec 2017 21:13:28 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Wed, 13 Dec 2017 21:13:28 GMT
recorded_with: VCR 3.0.3
